# Generated by Django 4.2.7 on 2025-11-17 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NASConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Tên NAS')),
                ('host', models.CharField(max_length=255, verbose_name='Địa chỉ IP/Domain')),
                ('port', models.IntegerField(default=5000, verbose_name='Port')),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('use_https', models.BooleanField(default=True, verbose_name='Sử dụng HTTPS')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cấu hình NAS',
                'verbose_name_plural': 'Cấu hình NAS',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage', models.FloatField(verbose_name='CPU Usage (%)')),
                ('memory_usage', models.FloatField(verbose_name='Memory Usage (%)')),
                ('memory_total', models.BigIntegerField(verbose_name='Total Memory (bytes)')),
                ('memory_used', models.BigIntegerField(verbose_name='Used Memory (bytes)')),
                ('disk_usage', models.JSONField(default=dict, verbose_name='Disk Usage')),
                ('network_stats', models.JSONField(blank=True, default=dict, verbose_name='Network Statistics')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian')),
                ('nas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_stats', to='nas_management.nasconfig', verbose_name='NAS')),
            ],
            options={
                'verbose_name': 'Thống kê hệ thống',
                'verbose_name_plural': 'Thống kê hệ thống',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['nas', '-timestamp'], name='nas_managem_nas_id_e7a8d6_idx')],
            },
        ),
        migrations.CreateModel(
            name='NASLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('syslog', 'System Log'), ('connectlog', 'Connection Log'), ('filexferlog', 'File Transfer Log')], default='syslog', max_length=20, verbose_name='Loại log')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20, verbose_name='Mức độ')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Danh mục')),
                ('message', models.TextField(verbose_name='Nội dung')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='Nguồn')),
                ('timestamp', models.DateTimeField(verbose_name='Thời gian')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('file_path', models.CharField(blank=True, max_length=1000, verbose_name='Đường dẫn file')),
                ('file_size', models.CharField(blank=True, max_length=100, verbose_name='Kích thước file')),
                ('file_name', models.CharField(blank=True, max_length=500, verbose_name='Tên file')),
                ('operation', models.CharField(blank=True, max_length=50, verbose_name='Thao tác')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='nas_management.nasconfig', verbose_name='NAS')),
            ],
            options={
                'verbose_name': 'Log NAS',
                'verbose_name_plural': 'Log NAS',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['nas', '-timestamp'], name='nas_managem_nas_id_0abd62_idx'), models.Index(fields=['level', '-timestamp'], name='nas_managem_level_a3bdc8_idx'), models.Index(fields=['log_type', '-timestamp'], name='nas_managem_log_typ_c31c1e_idx'), models.Index(fields=['nas', 'log_type', '-timestamp'], name='nas_managem_nas_id_991636_idx')],
                'unique_together': {('nas', 'log_type', 'timestamp', 'message')},
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('login_time', models.DateTimeField(verbose_name='Thời gian đăng nhập')),
                ('logout_time', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian đăng xuất')),
                ('is_success', models.BooleanField(default=True, verbose_name='Đăng nhập thành công')),
                ('failure_reason', models.CharField(blank=True, max_length=500, verbose_name='Lý do thất bại')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to='nas_management.nasconfig', verbose_name='NAS')),
            ],
            options={
                'verbose_name': 'Lịch sử đăng nhập',
                'verbose_name_plural': 'Lịch sử đăng nhập',
                'ordering': ['-login_time'],
                'indexes': [models.Index(fields=['-login_time'], name='nas_managem_login_t_799ca0_idx'), models.Index(fields=['username', '-login_time'], name='nas_managem_usernam_b12e83_idx'), models.Index(fields=['is_success', '-login_time'], name='nas_managem_is_succ_36bf9b_idx')],
            },
        ),
        migrations.CreateModel(
            name='FileOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('upload', 'Upload'), ('download', 'Download'), ('delete', 'Delete'), ('create_folder', 'Create Folder'), ('rename', 'Rename'), ('move', 'Move'), ('copy', 'Copy')], max_length=20, verbose_name='Thao tác')),
                ('file_path', models.CharField(max_length=1000, verbose_name='Đường dẫn file')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='Kích thước (bytes)')),
                ('is_success', models.BooleanField(default=True, verbose_name='Thành công')),
                ('error_message', models.TextField(blank=True, verbose_name='Lỗi')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian')),
                ('nas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_operations', to='nas_management.nasconfig', verbose_name='NAS')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
            ],
            options={
                'verbose_name': 'Thao tác file',
                'verbose_name_plural': 'Thao tác file',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['nas', '-timestamp'], name='nas_managem_nas_id_853973_idx'), models.Index(fields=['user', '-timestamp'], name='nas_managem_user_id_597a63_idx'), models.Index(fields=['operation', '-timestamp'], name='nas_managem_operati_d86009_idx')],
            },
        ),
    ]
