# Generated by Django 4.2.21 on 2025-11-07 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên công ty')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã công ty')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Công ty',
                'verbose_name_plural': 'Công ty',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên thiết bị')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Ký hiệu mã')),
                ('equipment_type', models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('router', 'Router'), ('switch', 'Switch'), ('printer', 'Máy in'), ('scanner', 'Máy quét'), ('other', 'Khác')], max_length=20, verbose_name='Loại thiết bị')),
                ('commission_date', models.DateField(blank=True, null=True, verbose_name='Thời điểm đưa vào sử dụng')),
                ('machine_name', models.CharField(blank=True, max_length=200, verbose_name='Tên máy')),
                ('operating_system', models.CharField(blank=True, max_length=200, verbose_name='Hệ điều hành')),
                ('system_manufacturer', models.CharField(blank=True, max_length=200, verbose_name='Nhà sản xuất')),
                ('system_model', models.CharField(blank=True, max_length=200, verbose_name='Model')),
                ('processor', models.CharField(blank=True, max_length=200, verbose_name='Bộ xử lý')),
                ('memory', models.CharField(blank=True, max_length=100, verbose_name='Bộ nhớ')),
                ('graphics_card', models.CharField(blank=True, max_length=200, verbose_name='Card đồ họa')),
                ('technical_specs', models.JSONField(blank=True, default=dict, verbose_name='Thông số kỹ thuật')),
                ('documentation', models.TextField(blank=True, verbose_name='Tài liệu hướng dẫn kèm theo')),
                ('dxdiag_file', models.FileField(blank=True, null=True, upload_to='dxdiag/', verbose_name='File DxDiag')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.company', verbose_name='Công ty')),
            ],
            options={
                'verbose_name': 'Thiết bị',
                'verbose_name_plural': 'Thiết bị',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateField(verbose_name='Ngày')),
                ('action_type', models.CharField(choices=[('repair', 'Sửa chữa'), ('replacement', 'Thay thế'), ('movement', 'Di chuyển'), ('liquidation', 'Thanh lý'), ('maintenance', 'Bảo trì'), ('upgrade', 'Nâng cấp'), ('other', 'Khác')], max_length=20, verbose_name='Loại hành động')),
                ('description', models.TextField(verbose_name='Nội dung chi tiết')),
                ('signed_by', models.CharField(max_length=200, verbose_name='Ký tên')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='equipment.equipment', verbose_name='Thiết bị')),
            ],
            options={
                'verbose_name': 'Lịch sử thiết bị',
                'verbose_name_plural': 'Lịch sử thiết bị',
                'ordering': ['-action_date', '-created_at'],
            },
        ),
    ]
