# Generated by Django 4.2.21 on 2025-11-07 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='current_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_using', to=settings.AUTH_USER_MODEL, verbose_name='Người đang sử dụng'),
        ),
        migrations.AlterField(
            model_name='equipmenthistory',
            name='action_type',
            field=models.CharField(choices=[('repair', 'Sửa chữa'), ('replacement', 'Thay thế'), ('movement', 'Di chuyển'), ('liquidation', 'Thanh lý'), ('maintenance', 'Bảo trì'), ('upgrade', 'Nâng cấp'), ('user_assignment', 'Giao máy cho người dùng'), ('user_return', 'Trả máy'), ('other', 'Khác')], max_length=20, verbose_name='Loại hành động'),
        ),
    ]
