# Generated by Django 4.2.21 on 2025-11-07 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_equipment_current_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='monitor_model',
            field=models.CharField(blank=True, max_length=200, verbose_name='Monitor Model'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='monitor_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Monitor Name'),
        ),
    ]
