# Generated by Django 4.2.21 on 2025-11-07 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_equipment_monitor_model_equipment_monitor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='region',
            field=models.CharField(choices=[('MN', 'Miền Nam'), ('MT', 'Miền Trung'), ('MB', 'Miền Bắc')], default='MN', max_length=2, verbose_name='Miền'),
        ),
    ]
