# Generated by Django 4.2.21 on 2025-11-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_equipment_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='paging',
            field=models.CharField(blank=True, help_text='Thông tin paging cho thiết bị', max_length=200, verbose_name='Paging'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='storage',
            field=models.CharField(blank=True, help_text='Ví dụ: SSD 256GB, HDD 1TB', max_length=200, verbose_name='HDD/SSD'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('router', 'Router'), ('switch', 'Switch'), ('printer', 'Máy in'), ('scanner', 'Máy quét'), ('server', 'Server'), ('storage', 'Bộ lưu trữ'), ('hardware', 'Phần cứng'), ('chamcong', 'Chấm công'), ('other', 'Khác')], max_length=20, verbose_name='Loại thiết bị'),
        ),
    ]
