# Generated by Django 4.2.21 on 2025-11-10 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_equipment_paging_equipment_storage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='paging',
        ),
    ]
