# Generated by Django 4.2.21 on 2025-11-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_remove_equipment_paging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('router', 'Router'), ('switch', 'Switch'), ('printer', 'Máy in'), ('scanner', 'Máy quét'), ('server', 'Server'), ('storage', 'Bộ lưu trữ'), ('hardware', 'Phần cứng'), ('chamcong', 'Chấm công'), ('camera', 'Camera'), ('daughi', 'Đầu ghi'), ('other', 'Khác')], max_length=20, verbose_name='Loại thiết bị'),
        ),
    ]
