# Generated by Django 4.2.21 on 2025-11-13 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0007_alter_equipment_equipment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên dịch vụ')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('expiry_date', models.DateField(verbose_name='Ngày hết hạn')),
                ('renewal_period', models.IntegerField(default=12, help_text='Số tháng gia hạn mỗi lần', verbose_name='Chu kỳ gia hạn (tháng)')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Chi phí gia hạn (VND)', max_digits=15, null=True, verbose_name='Chi phí')),
                ('provider', models.CharField(blank=True, max_length=200, verbose_name='Nhà cung cấp')),
                ('provider_contact', models.CharField(blank=True, max_length=200, verbose_name='Liên hệ nhà cung cấp')),
                ('status', models.CharField(choices=[('active', 'Đang hoạt động'), ('expired', 'Đã hết hạn'), ('cancelled', 'Đã hủy')], default='active', max_length=20, verbose_name='Trạng thái')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('auto_renewal', models.BooleanField(default=False, verbose_name='Tự động gia hạn')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.company', verbose_name='Công ty')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Gia hạn dịch vụ',
                'verbose_name_plural': 'Gia hạn dịch vụ',
                'ordering': ['expiry_date', 'renewal_type'],
            },
        ),
        migrations.CreateModel(
            name='RenewalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên loại')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự sắp xếp')),
            ],
            options={
                'verbose_name': 'Loại dịch vụ',
                'verbose_name_plural': 'Loại dịch vụ',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RenewalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewal_date', models.DateField(verbose_name='Ngày gia hạn')),
                ('old_expiry_date', models.DateField(verbose_name='Ngày hết hạn cũ')),
                ('new_expiry_date', models.DateField(verbose_name='Ngày hết hạn mới')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Chi phí gia hạn')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('renewal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='renewals.renewal', verbose_name='Dịch vụ')),
                ('renewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người gia hạn')),
            ],
            options={
                'verbose_name': 'Lịch sử gia hạn',
                'verbose_name_plural': 'Lịch sử gia hạn',
                'ordering': ['-renewal_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='renewal',
            name='renewal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renewals.renewaltype', verbose_name='Loại dịch vụ'),
        ),
        migrations.AddField(
            model_name='renewal',
            name='responsible_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals_responsible', to=settings.AUTH_USER_MODEL, verbose_name='Người phụ trách'),
        ),
    ]
