# Generated by Django 4.2.21 on 2025-11-10 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên công ty')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã công ty')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Công ty',
                'verbose_name_plural': 'Công ty',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên phòng ban')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='tickets.company', verbose_name='Công ty')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdepartments', to='tickets.department', verbose_name='Phòng ban cha')),
            ],
            options={
                'verbose_name': 'Phòng ban',
                'verbose_name_plural': 'Phòng ban',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Số ticket')),
                ('title', models.CharField(max_length=500, verbose_name='Tiêu đề')),
                ('description', models.TextField(verbose_name='Mô tả chi tiết')),
                ('requester_name', models.CharField(max_length=200, verbose_name='Tên người yêu cầu')),
                ('requester_email', models.EmailField(max_length=254, verbose_name='Email người yêu cầu')),
                ('requester_phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('priority', models.CharField(choices=[('critical', '🔹 Khẩn cấp (Critical/P1)'), ('high', '🔸 Cao (High/P2)'), ('medium', '🟡 Trung bình (Medium/P3)'), ('low', '⚪ Thấp (Low/P4)')], default='medium', max_length=20, verbose_name='Mức độ ưu tiên')),
                ('status', models.CharField(choices=[('new', 'Mới tạo'), ('assigned', 'Đã phân công'), ('in_progress', 'Đang xử lý'), ('resolved', 'Đã xử lý'), ('closed', 'Đã đóng'), ('cancelled', 'Đã hủy')], default='new', max_length=20, verbose_name='Trạng thái')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xử lý xong')),
                ('resolution', models.TextField(blank=True, verbose_name='Kết quả xử lý')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('repeat_count', models.IntegerField(default=0, verbose_name='Số lần lặp lại trong tháng')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Người được phân công')),
            ],
            options={
                'verbose_name': 'Ticket hỗ trợ',
                'verbose_name_plural': 'Ticket hỗ trợ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('is_internal', models.BooleanField(default=False, help_text='Chỉ IT mới thấy được', verbose_name='Ghi chú nội bộ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_comments', to=settings.AUTH_USER_MODEL, verbose_name='Người viết')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Bình luận ticket',
                'verbose_name_plural': 'Bình luận ticket',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên loại yêu cầu')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='tickets.ticketcategory', verbose_name='Loại cha')),
            ],
            options={
                'verbose_name': 'Loại yêu cầu',
                'verbose_name_plural': 'Loại yêu cầu',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ticket_attachments/%Y/%m/', verbose_name='File')),
                ('filename', models.CharField(max_length=255, verbose_name='Tên file')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày upload')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket', verbose_name='Ticket')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Người upload')),
            ],
            options={
                'verbose_name': 'File đính kèm',
                'verbose_name_plural': 'File đính kèm',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.ticketcategory', verbose_name='Loại yêu cầu'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.company', verbose_name='Công ty'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.department', verbose_name='Phòng ban'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Người yêu cầu'),
        ),
    ]
