# Generated by Django 4.2.21 on 2025-11-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Phòng ban', 'verbose_name_plural': 'Phòng ban'},
        ),
        migrations.AlterModelOptions(
            name='ticketcategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Loại yêu cầu', 'verbose_name_plural': 'Loại yêu cầu'},
        ),
        migrations.AddField(
            model_name='department',
            name='order',
            field=models.IntegerField(default=0, help_text='Số càng nhỏ càng hiển thị trước. Các item cùng parent sẽ được sắp xếp theo số này.', verbose_name='Thứ tự sắp xếp'),
        ),
        migrations.AddField(
            model_name='ticketcategory',
            name='order',
            field=models.IntegerField(default=0, help_text='Số càng nhỏ càng hiển thị trước. Các item cùng parent sẽ được sắp xếp theo số này.', verbose_name='Thứ tự sắp xếp'),
        ),
    ]
